=== martingleich/Iec61131/SourceGenerator.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Objects">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="TokenInterfaces">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="TokenInterface" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Name"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="TokenClasses">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="TokenWithoutValueClass" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Name"/>
                    <xs:element type="xs:string" name="Generating"/>
                    <xs:element type="xs:string" name="Interface" maxOccurs="unbounded" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="TokenKeywordClass" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Name"/>
                    <xs:element type="xs:string" name="Generating"/>
                    <xs:element type="xs:string" name="Interface" maxOccurs="unbounded" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="TokenWithValueClass" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Name"/>
                    <xs:element type="xs:string" name="ValueType"/>
                    <xs:element type="xs:string" name="Interface" minOccurs="0"/>
                    <xs:element type="xs:string" name="DefaultValue" minOccurs="0" maxOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="SyntaxInterfaces">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="SyntaxInterface" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Name"/>
					<xs:element type="xs:string" name="Extends" minOccurs="0" maxOccurs="1"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="SyntaxClasses">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="SyntaxClass" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Name"/>
                    <xs:element type="xs:string" name="Interface" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="Element" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
						  <xs:element type="xs:string" name="Name"/>
                          <xs:element name="Kind" minOccurs="0" maxOccurs="1">
                            <xs:simpleType>
                              <xs:restriction base="xs:string">
                                <xs:enumeration value="Nullable"/>
                                <xs:enumeration value="Array"/>
                                <xs:enumeration value="CommaSeparated"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
						  <xs:element type="xs:string" name="Type"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== martingleich/Iec61131/SourceGenerator.xml
<?xml version="1.0" encoding="utf-8"?>
<Objects xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="SourceGenerator SourceGenerator.xsd">
  <TokenInterfaces>
    <TokenInterface>
      <Name>IBinaryOperatorToken</Name>
    </TokenInterface>
    <TokenInterface>
      <Name>IUnaryOperatorToken</Name>
    </TokenInterface>
    <TokenInterface>
      <Name>IVarDeclKindToken</Name>
    </TokenInterface>
    <TokenInterface>
      <Name>IPouKindToken</Name>
    </TokenInterface>
    <TokenInterface>
      <Name>ILiteralToken</Name>
    </TokenInterface>
    <TokenInterface>
      <Name>IParameterKindToken</Name>
    </TokenInterface>
    <TokenInterface>
      <Name>IParenthesisedOperatorToken</Name>
    </TokenInterface>
    <TokenInterface>
      <Name>IBuiltInTypeToken</Name>
    </TokenInterface>
  </TokenInterfaces>
  <TokenClasses>
    <!--Token without value-->
    <TokenWithoutValueClass>
      <Name>CommaToken</Name>
      <Generating>,</Generating>
    </TokenWithoutValueClass>
    <TokenWithoutValueClass>
      <Name>AssignToken</Name>
      <Generating>:=</Generating>
      <Interface>IParameterKindToken</Interface>
    </TokenWithoutValueClass>
    <TokenWithoutValueClass>
      <Name>DerefToken</Name>
      <Generating>^</Generating>
    </TokenWithoutValueClass>
    <TokenWithoutValueClass>
      <Name>EqualToken</Name>
      <Generating>=</Generating>
      <Interface>IBinaryOperatorToken</Interface>
    </TokenWithoutValueClass>
    <TokenWithoutValueClass>
      <Name>LessEqualToken</Name>
      <Generating>&lt;=</Generating>
      <Interface>IBinaryOperatorToken</Interface>
    </TokenWithoutValueClass>
    <TokenWithoutValueClass>
      <Name>LessToken</Name>
      <Generating>&lt;</Generating>
      <Interface>IBinaryOperatorToken</Interface>
    </TokenWithoutValueClass>
    <TokenWithoutValueClass>
      <Name>GreaterToken</Name>
      <Generating>&gt;</Generating>
      <Interface>IBinaryOperatorToken</Interface>
    </TokenWithoutValueClass>
    <TokenWithoutValueClass>
      <Name>GreaterEqualToken</Name>
      <Generating>&gt;=</Generating>
      <Interface>IBinaryOperatorToken</Interface>
    </TokenWithoutValueClass>
    <TokenWithoutValueClass>
      <Name>UnEqualToken</Name>
      <Generating>&lt;&gt;</Generating>
      <Interface>IBinaryOperatorToken</Interface>
    </TokenWithoutValueClass>
    <TokenWithoutValueClass>
      <Name>DoubleArrowToken</Name>
      <Generating>=&gt;</Generating>
      <Interface>IParameterKindToken</Interface>
    </TokenWithoutValueClass>
    <TokenWithoutValueClass>
      <Name>DotToken</Name>
      <Generating>.</Generating>
    </TokenWithoutValueClass>
    <TokenWithoutValueClass>
      <Name>SemicolonToken</Name>
      <Generating>;</Generating>
    </TokenWithoutValueClass>
    <TokenWithoutValueClass>
      <Name>DotsToken</Name>
      <Generating>..</Generating>
    </TokenWithoutValueClass>
    <TokenWithoutValueClass>
      <Name>ColonToken</Name>
      <Generating>:</Generating>
    </TokenWithoutValueClass>
    <TokenWithoutValueClass>
      <Name>PlusToken</Name>
      <Generating>+</Generating>
      <Interface>IBinaryOperatorToken</Interface>
    </TokenWithoutValueClass>
    <TokenWithoutValueClass>
      <Name>MinusToken</Name>
      <Generating>-</Generating>
      <Interface>IUnaryOperatorToken</Interface>
      <Interface>IBinaryOperatorToken</Interface>
    </TokenWithoutValueClass>
    <TokenWithoutValueClass>
      <Name>StarToken</Name>
      <Generating>*</Generating>
      <Interface>IBinaryOperatorToken</Interface>
    </TokenWithoutValueClass>
    <TokenWithoutValueClass>
      <Name>SlashToken</Name>
      <Generating>/</Generating>
      <Interface>IBinaryOperatorToken</Interface>
    </TokenWithoutValueClass>
    <TokenWithoutValueClass>
      <Name>PowerToken</Name>
      <Generating>**</Generating>
      <Interface>IBinaryOperatorToken</Interface>
    </TokenWithoutValueClass>
    <TokenWithoutValueClass>
      <Name>EndToken</Name>
      <Generating></Generating>
    </TokenWithoutValueClass>
    <!--Alls kinds of parenthesis-->
    <TokenWithoutValueClass>
      <Name>ParenthesisOpenToken</Name>
      <Generating>(</Generating>
    </TokenWithoutValueClass>
    <TokenWithoutValueClass>
      <Name>ParenthesisCloseToken</Name>
      <Generating>)</Generating>
    </TokenWithoutValueClass>
    <TokenWithoutValueClass>
      <Name>BracketOpenToken</Name>
      <Generating>[</Generating>
    </TokenWithoutValueClass>
    <TokenWithoutValueClass>
      <Name>BracketCloseToken</Name>
      <Generating>]</Generating>
    </TokenWithoutValueClass>
    <TokenKeywordClass>
      <Name>VarToken</Name>
      <Generating>VAR</Generating>
      <Interface>IVarDeclKindToken</Interface>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>EndVarToken</Name>
      <Generating>END_VAR</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>VarInputToken</Name>
      <Generating>VAR_INPUT</Generating>
      <Interface>IVarDeclKindToken</Interface>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>VarGlobalToken</Name>
      <Generating>VAR_GLOBAL</Generating>
      <Interface>IVarDeclKindToken</Interface>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>VarOutToken</Name>
      <Generating>VAR_OUTPUT</Generating>
      <Interface>IVarDeclKindToken</Interface>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>VarInOutToken</Name>
      <Generating>VAR_IN_OUT</Generating>
      <Interface>IVarDeclKindToken</Interface>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>VarTempToken</Name>
      <Generating>VAR_TEMP</Generating>
      <Interface>IVarDeclKindToken</Interface>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>ProgramToken</Name>
      <Generating>PROGRAM</Generating>
      <Interface>IPouKindToken</Interface>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>FunctionToken</Name>
      <Generating>FUNCTION</Generating>
      <Interface>IPouKindToken</Interface>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>FunctionBlockToken</Name>
      <Generating>FUNCTION_BLOCK</Generating>
      <Interface>IPouKindToken</Interface>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>MethodToken</Name>
      <Generating>METHOD</Generating>
      <Interface>IPouKindToken</Interface>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>PointerToken</Name>
      <Generating>POINTER</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>ArrayToken</Name>
      <Generating>ARRAY</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>StringToken</Name>
      <Generating>STRING</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>OfToken</Name>
      <Generating>OF</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>IfToken</Name>
      <Generating>IF</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>ThenToken</Name>
      <Generating>THEN</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>EndIfToken</Name>
      <Generating>END_IF</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>ElsifToken</Name>
      <Generating>ELSIF</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>ElseToken</Name>
      <Generating>ELSE</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>WhileToken</Name>
      <Generating>WHILE</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>EndWhileToken</Name>
      <Generating>END_WHILE</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>RepeatToken</Name>
      <Generating>REPEAT</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>UntilToken</Name>
      <Generating>UNTIL</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>EndRepeatToken</Name>
      <Generating>END_REPEAT</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>ExitToken</Name>
      <Generating>EXIT</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>ContinueToken</Name>
      <Generating>CONTINUE</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>ReturnToken</Name>
      <Generating>RETURN</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>ForToken</Name>
      <Generating>FOR</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>ToToken</Name>
      <Generating>TO</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>ByToken</Name>
      <Generating>BY</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>EndForToken</Name>
      <Generating>END_FOR</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>DoToken</Name>
      <Generating>DO</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>CaseToken</Name>
      <Generating>CASE</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>EndCaseToken</Name>
      <Generating>END_CASE</Generating>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>AndToken</Name>
      <Generating>AND</Generating>
      <Interface>IBinaryOperatorToken</Interface>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>XorToken</Name>
      <Generating>XOR</Generating>
      <Interface>IBinaryOperatorToken</Interface>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>OrToken</Name>
      <Generating>OR</Generating>
      <Interface>IBinaryOperatorToken</Interface>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>NotToken</Name>
      <Generating>NOT</Generating>
      <Interface>IUnaryOperatorToken</Interface>
    </TokenKeywordClass>
    <TokenKeywordClass>
      <Name>ConstantToken</Name>
      <Generating>CONSTANT</Generating>
    </TokenKeywordClass>
